language: r
sudo : false
cache: packages


r:
  - release

r_packages:
  - mlr
  - ParamHelpers
  - smoof
  - mlrMBO
  - xgboost
  - DiceKriging
  - parallelMap
  - rgenoud

warnings_are_errors: true
